apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: mlops-spark-operator
build:
  artifacts:
  - image: mlops-spark-operator
    context: .
    docker:
      dockerfile: docker/Dockerfile
manifests:
  rawYaml:
    - deploy/namespace.yaml
    - deploy/sparknotebook-crd.yaml
    - deploy/rbac.yaml
    - deploy/configmap.yaml
    - deploy/deployment.yaml

