apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-spark-operator
  namespace: mlops-spark-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlops-spark-operator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update", "get", "list", "watch"]
- apiGroups: ["mlops.example.com"]
  resources: ["sparknotebooks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["mlops.example.com"]
  resources: ["sparknotebooks/status"]
  verbs: ["update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]  # Add permissions to access configmaps
  verbs: ["get", "list", "watch"]  # Ensure "get" is included

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mlops-spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlops-spark-operator
subjects:
- kind: ServiceAccount
  name: mlops-spark-operator
  namespace: mlops-spark-operator
