apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlops-spark-operator
rules:
  # Permissions for events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update", "get", "list", "watch"]
  
  # Permissions for SparkNotebook CRDs in mlops.example.com
  - apiGroups: ["mlops.example.com"]
    resources: ["sparknotebooks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["mlops.example.com"]
    resources: ["sparknotebooks/status"]
    verbs: ["update"]

  # Permissions for custom resource definitions
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # Permissions for ConfigMaps in the core API group
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Permissions for PodDefaults in the kubeflow.org API group
  - apiGroups: ["kubeflow.org"]
    resources: ["poddefaults"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mlops-spark-operator-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mlops-spark-operator  # The service account in the operator's namespace
roleRef:
  kind: ClusterRole
  name: mlops-spark-operator
  apiGroup: rbac.authorization.k8s.io
